export const CART_ITEM_LOADING = "CART_ITEM_LOADING";
export const CART_ITEM_ADD = "CART_ITEM_ADD";
export const CART_ITEM_ERROR = "CART_ITEM_ERROR";
export const CART_ITEM_DELETE = "CART_ITEM_DELETE";
