export const FETCH_POST_LOADING = "FETCH_POST_LOADING";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_ERROR = "FETCH_POST_ERROR";

//Dropdown Toggler

export const TOGGLE_OPEN = "TOGGLE_OPEN";
export const TOGGLE_CLOSE = "TOGGLE_CLOSE";
