export const FETCH_SINGLE_PRODUCT_LOADING = "FETCH_SINGLE_PRODUCT_LOADING";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_ERROR = "FETCH_SINGLE_PRODUCT_ERROR";
